### ISSUE TITLE
Windows Plot Mover

### ISSUE THREAD

**Issue by zhurakovsky01** [Ron-ski/Windows-Plot-Mover#2]
Hello! Can you make it work with the *.fpt extension? I would be very grateful

**Comment by zhurakovsky01** [comment]
This is the expansion of the plots NoSSD

**Comment by Ron-ski** [comment]
Hi, I've added the ability to move NoSSD plot files, selection is by the two drop down lists on the main page. One selects the format to move, the other the format to delete if applicable.

I haven't had time to extensively test this, but basic testing shows it works.

**Comment by zhurakovsky01** [comment]
Thank you. Excellent result
