### ISSUE TITLE
windows 10 下报毒

### ISSUE THREAD

**Issue by zhanMM** [Ron-ski/Windows-Plot-Mover#3]
![image](https://github.com/Ron-ski/Windows-Plot-Mover/assets/83106600/96a6f1b2-2f99-414c-942f-63853e0fd55c)

**Comment by Ron-ski** [comment]
Please submit the program as a false positive at https://www.microsoft.com/en-us/wdsi/filesubmission you may need to use Microsoft Edge.

You can also scan the files at www.virustotal.com 

Seems I need to scan and submit to any that flag it as trojan/virus prior to release, what a pain.
